### ISSUE TITLE
Deprecated functionality exception in Zend_Pdf component

### ISSUE THREAD

**Issue by mam08ixo** [magento/zf1#44]
### Preconditions

1. Magento 2.4.4 with PHP 8.1
2. PHP error reporting set to ([`E_ALL`](https://github.com/magento/magento2/blob/2.4.4/app/bootstrap.php#L10))

### Steps to reproduce

1. Create a shipment with shipping label
2. In shipments grid, select the shipment and execute the _Print Shipping Labels_ mass action

### Expected result

Shipping label document opens.

### Actual result

![zend_pdf_deprecated_functionality](https://user-images.githubusercontent.com/1771622/164754026-b505f77b-0d2e-4fef-9810-8dc38963ad2e.png)

Error message is displayed:

> Deprecated Functionality: Optional parameter $genNum declared before required parameter $factory is implicitly treated as a required parameter in /var/www/html/vendor/magento/zendframework1/library/Zend/Pdf/Element/Reference.php on line 91

https://github.com/magento/zf1/blob/f241f5be1820784e7f54a36115e1324b5bb8a4ab/library/Zend/Pdf/Element/Reference.php#L91

The entrypoint to the error seems to be `Zend_Pdf::parse`.

**Comment by xmav** [comment]
Hi @mam08ixo 
Please check if issue still exists with https://github.com/magento/zf1/releases/tag/1.15.1

**Comment by xmav** [comment]
Closing for now. Feel free to reopen if needed
